    console.log(3);
    var x = 5;
    var y = 6;
    var z = x + y;
    var myOfficeAddress = "‘at diu’";
    var onionPrice = 30;
    var orangePrice = 120;
    var eggPrice = 29;
    var eggQuantity = 7;
    var eggPriceMultiplier = eggPrice * eggQuantity;
    var totalPrice = onionPrice + orangePrice;
    var priceDifference = onionPrice - orangePrice;
    console.log(priceDifference);
    console.log(eggPriceMultiplier);
    var moneyAvailable = 100;
    var orangePrice = 10;
    var division = moneyAvailable / orangePrice;
    console.log(division);
    // console.log(onionPrice);
    // console.log(orangePrice);
    // console.log(onionPrice + orangePrice);
    // console.log(totalPrice);
